"""change user model

Revision ID: a75f553f54a4
Revises: 3fe88cd6ac76
Create Date: 2024-10-13 14:42:51.414433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a75f553f54a4'
down_revision = '3fe88cd6ac76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=False))
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.String(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'Undefined'::character varying"))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'second_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('second_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('users', 'password',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=13),
               existing_nullable=False,
               existing_server_default=sa.text("'Undefined'::character varying"))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
