name: Python payroll system
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.3
        env:
          POSTGRES_USER: usertest
          POSTGRES_PASSWORD: password
          POSTGRES_DB: payrollsystem
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: "3.12"
    - name: Install dependencies and test
      env:
        DB_USER: usertest
        DB_PASSWORD: password
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
        DB_NAME: payrollsystem
        TEST_DB_NAME: payrollsystem
        SECRET_KEY: ""
        AWS_KEY: ""
        ASW_SECRET: ""
        BUCKET_NAME: ""
        BUCKET_REGION: ""
        EMAIL: ""
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        export PGPASSWORD="password"
        pytest
